---
#------------------------------------------------------------------------------
#  
# Playbook for 201 Automation Workshop - Runs AFTER Terraform has built Infra.
#
#------------------------------------------------------------------------------
#   Terraform should create/populate the inventory file ../inventory/bigips.ini
#   Run 'ansible-playbook ./main.yaml -i ../inventory/bigips.ini --ask-vault-pass'
#------------------------------------------------------------------------------

- name: CONFIGURE DEPLOYED BIG-IP
  hosts: bigips
  connection: local
  gather_facts: no

  environment:
    AWS_ACCESS_KEY_ID: "{{ ec2_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ ec2_secret_key }}"
    AWS_REGION: "{{ aws_region }}"

#------------------------------------------------------------------------------
# Load Variables from files 
#------------------------------------------------------------------------------

  vars_files:

    - ../../../creds/aws_creds_personal.yaml
    - ../vars/vars.yaml

  
#------------------------------------------------------------------------------
# End variables
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Start tasks
#------------------------------------------------------------------------------

  tasks:

  - include_tasks: ../tasks/tasks-01-aws-eni-ips.yaml
  - include_tasks: ../tasks/tasks-02-deploy-do.yaml
  - include_tasks: ../tasks/tasks-03-deploy-as3.yaml
  - include_tasks: ../tasks/tasks-04-outputs.yaml

#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...