---
#------------------------------------------------------------------------------
# Playbook to DELETE Ansible Components.
#
#   Requires pyvmomi python library
#------------------------------------------------------------------------------

- name: CONFIGURE DEPLOYED BIG-IP
  hosts: bigips
  connection: local
  gather_facts: no

  environment:
    AWS_ACCESS_KEY_ID: "{{ ec2_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ ec2_secret_key }}"
    AWS_REGION: "{{ aws_region }}"

#------------------------------------------------------------------------------
# Load Variables from files 
#------------------------------------------------------------------------------

  vars_files:

    - ../../../creds/aws_creds.yaml
    - ../vars/vars.yaml

  
#------------------------------------------------------------------------------
# End variables
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Start tasks
#------------------------------------------------------------------------------

  tasks:

  - include_tasks: ../tasks/tasks-11-remove-aws-static-eni-ips.yaml

#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...