---
#------------------------------------------------------------------------------
# Start tasks
#------------------------------------------------------------------------------


- name: GET ENI FACTS
  ec2_eni_facts:
    filters:
      network-interface-id: "{{ aws_pub_eni_id }}"
  register: ec2_eni_facts


- name: DEBUG OUTPUT EXISTING PUBLIC IPS
  debug:
    msg: "Public IP {{ index }}: {{ item.association.public_ip }}"
  loop: "{{ ec2_eni_facts.network_interfaces[0].private_ip_addresses }}"
  loop_control:
    index_var: index


- name: DISASSOCIATE EIPS FROM ENI
  ec2_eip:
    public_ip: "{{ item.association.public_ip }}"
    device_id: "{{ aws_pub_eni_id }}"
    private_ip_address: "{{ item.private_ip_address }}"
    in_vpc: true
    state: absent
    release_on_disassociation: yes
  loop: "{{ ec2_eni_facts.network_interfaces[0].private_ip_addresses }}"
  loop_control:
    index_var: index


- name: OUTPUT ADVICE
  debug:
    msg: "You should now be able to delete the inrastructure with terraform destroy"

#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...